import numpy as np
import traci
import gymnasium as gym
from gymnasium import spaces
from collections import defaultdict


class OSMTrafficEnv(gym.Env):
    """
    Multi-agent traffic signal control on a real OpenStreetMap network.

    The observation and action interface is identical to GridTrafficEnv,
    enabling direct policy transfer from the synthetic 3x3 grid.

    Key differences from GridTrafficEnv:
        - TLS IDs are taken directly from the OSM-generated network.
        - Lane counts per intersection vary; padded to OBS_DIM with
          "dummy_lane" entries that always return zero halting vehicles.
        - Phase programs are generated by netconvert from real OSM data.

    Args:
        cfg:             Path to the .sumocfg file for the OSM network.
        agent_lane_map:  Dict mapping agent index (0-8) to a list of
                         OBS_DIM lane IDs. Built by inspecting the
                         sumolib network in Notebook 4 Cell 3.
        gui:             Launch sumo-gui if True.
    """

    N_AGENTS  = 9
    OBS_DIM   = 8
    DELTA     = 5
    MIN_GREEN = 10
    YELLOW    = 4
    MAX_Q     = 30.0
    EP_LEN    = 3600

    def __init__(self, cfg, agent_lane_map=None, gui=False):
        super().__init__()
        self.cfg            = cfg
        self.binary         = "sumo-gui" if gui else "sumo"
        self.agent_lane_map = agent_lane_map or {}

        self.observation_space = spaces.Box(
            0.0, 1.0,
            shape=(self.N_AGENTS, self.OBS_DIM),
            dtype=np.float32)
        self.action_space = spaces.MultiDiscrete([2] * self.N_AGENTS)

        self._tls_ids   = []
        self._gp_map    = {}
        self._g2y_map   = {}
        self._cur_map   = {}
        self._timer_map = {}
        self._step      = 0

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        try:
            traci.close()
        except Exception:
            pass
        traci.start([self.binary, "-c", self.cfg,
                     "--no-step-log", "true", "--no-warnings", "true"])
        all_tls = list(traci.trafficlight.getIDList())
        self._tls_ids = [all_tls[i % len(all_tls)]
                         for i in range(self.N_AGENTS)]
        for i, tls in enumerate(self._tls_ids):
            self._gp_map[i]    = self._get_gp(tls)
            self._g2y_map[i]   = self._get_g2y(tls)
            self._cur_map[i]   = 0
            self._timer_map[i] = 0
            traci.trafficlight.setPhase(tls, self._gp_map[i][0])
        self._step = 0
        for _ in range(30):
            traci.simulationStep()
        self._step = 30
        return self._obs_all(), {}

    def _get_gp(self, tls):
        logic = traci.trafficlight.getCompleteRedYellowGreenDefinition(tls)[0]
        gp    = [i for i, p in enumerate(logic.phases)
                 if "G" in p.state and "y" not in p.state.lower()]
        return gp if gp else [0]

    def _get_g2y(self, tls):
        logic  = traci.trafficlight.getCompleteRedYellowGreenDefinition(tls)[0]
        phases = logic.phases
        gp     = self._get_gp(tls)
        g2y    = {}
        for g in gp:
            nxt = g + 1
            if nxt < len(phases) and "y" in phases[nxt].state.lower():
                g2y[g] = nxt
            else:
                for j, p in enumerate(phases):
                    if "y" in p.state.lower():
                        g2y[g] = j
                        break
            if g not in g2y:
                g2y[g] = g
        return g2y

    def step(self, actions):
        for i in range(self.N_AGENTS):
            action  = int(actions[i])
            gp      = self._gp_map[i]
            desired = gp[min(action, len(gp) - 1)]
            current = gp[self._cur_map[i]]
            tls     = self._tls_ids[i]
            if desired != current and self._timer_map[i] >= self.MIN_GREEN:
                yellow = self._g2y_map[i].get(current, current)
                traci.trafficlight.setPhase(tls, yellow)
                for _ in range(self.YELLOW):
                    traci.simulationStep()
                    self._step += 1
                self._cur_map[i]   = min(action, len(gp) - 1)
                self._timer_map[i] = 0
                traci.trafficlight.setPhase(tls, desired)

        total_wait = defaultdict(float)
        for _ in range(self.DELTA):
            traci.simulationStep()
            self._step += 1
            for i in range(self.N_AGENTS):
                for lane in self.agent_lane_map.get(i, []):
                    if lane and lane != "dummy_lane":
                        try:
                            total_wait[i] += float(
                                traci.lane.getLastStepHaltingNumber(lane))
                        except Exception:
                            pass

        for i in range(self.N_AGENTS):
            self._timer_map[i] += self.DELTA

        avg_waits   = {i: total_wait[i] / self.DELTA
                       for i in range(self.N_AGENTS)}
        rewards     = np.array([-avg_waits[i] / 50.0
                                 for i in range(self.N_AGENTS)],
                                dtype=np.float32)
        global_wait = float(np.mean(list(avg_waits.values())))
        terminated  = self._step >= self.EP_LEN
        if terminated:
            try:
                traci.close()
            except Exception:
                pass
        obs  = self._obs_all()
        info = {
            "avg_wait":     global_wait,
            "global_state": obs.flatten(),
            "step":         self._step,
        }
        return obs, rewards, terminated, False, info

    def _obs_all(self):
        obs = np.zeros((self.N_AGENTS, self.OBS_DIM), dtype=np.float32)
        for i in range(self.N_AGENTS):
            for j, lane in enumerate(self.agent_lane_map.get(i, [])):
                if lane and lane != "dummy_lane":
                    try:
                        obs[i, j] = min(
                            traci.lane.getLastStepHaltingNumber(lane)
                            / self.MAX_Q, 1.0)
                    except Exception:
                        pass
        return obs

    def global_state(self):
        """Returns flattened (72,) global observation for MAPPO critic."""
        return self._obs_all().flatten()

    def close(self):
        try:
            traci.close()
        except Exception:
            pass
